### ISSUE TITLE
feat(xprovider): fetch by blockhash, not height

### ISSUE THREAD

**Issue by ttarsi** [omni-network/omni#1313]
We should [query for msgs](https://github.com/omni-network/omni/blob/cbc8df960d848fad213c26c7568f2597a2f646da/lib/xchain/provider/fetch.go#L297) and receipts by blockhash, not height. This gives us a bit more confidence in what we query and is more reorg-resistant.

**Comment by arajasek** [comment]
@corverroos I've hit a bit of a blocker here. Although geth's [FilterQuery](https://github.com/ethereum/go-ethereum/blob/9d537f543990d9013d73433dc58fd0e985d9b2b6/interfaces.go#L171) allows one to specify a `BlockHash`, this is abstracted away behind the `BoundContract` type, which only allows queries based on height (through the [FilterOpts](https://github.com/ethereum/go-ethereum/blob/ba2dd9385c2a51134e520083dc732787a813b107/accounts/abi/bind/base.go#L75) type). 

We're a little restricted by the geth interfaces here. I don't have an easy way to do this without some major refactor or forking geth, neither of which we likely want to do.

I wonder whether you have any ideas here?

**Comment by arajasek** [comment]
^Discussed offline, Corver pointed out that I could just use the RPC client
