### ISSUE TITLE
Refund excess amount paid for fees

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1413]
See Sigma Prime report OMP-10

**Comment by kevinhalliday** [comment]
Why we are closing:

This adds some complexity, not so much to our portal contract, but to xdapp developers, without adding too much value

**The Complexity**

Having xapp contracts receive fee refunds forces xapp developers to have to differentiate  ETH they receive from fee refunds, and ETH they receive from other sources (ETH here referring to native token).

**Why it does not add much value**

If they charge their users for fees, and want to handle refunding, they'd need do the same checks we do, in which case the refund logic would be duplicate unless they just wanted to pocket the fees their users overpaid. If they are using a funded contract, then they'd be calculating the fee synchronously anyways, so there would be no refund
