### ISSUE TITLE
Mainnet V2

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1444]
- Expand Omni Network to include alternative Data Availability systems like EigenDA and Celestia.
- Attestation sharding to increase the rollup capacity of the network by an order of magnitude.
- Onboard MPC providers to provide institutional users with access to all Ethereum rollups.
https://www.binance.com/en/research/projects/omni

**Comment by ttarsi** [comment]
going to close this in favor of splitting it into separate features, "mainnet v2" scope is not yet determined
