### ISSUE TITLE
Figure out how to provide proper gas limit for OmniAVS xcall with variable number of validators

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1445]
*Problem to Solve*

Our OmniAVS contract currently estimates gas for `EthStakeInbox.sync` using a base gas limit of `75k` and a per operator gas limit of `50k`. These are estimations. Once we implement `EthStakeInbox.sync`, we need to determine exact gas limits.

*Proposed Solution*

Write tests for EthStakeInbox.sync to get new gas limits. Confirm gas limits in devnet / staging / testnet.

**Comment by ttarsi** [comment]
Closing as this will be significantly refactored in when the full AVS implementation is designed

**Comment by ttarsi** [comment]
Closing as this will be significantly refactored in when the full AVS implementation is designed
