### ISSUE TITLE
Add names and block periods on-chain into the portal registry

### ISSUE THREAD

**Issue by ttarsi** [omni-network/omni#1446]
- Why?
  - As is
    - Store metadata in the binary, we hardcode the metadata
    - Issues with upgrades if we stay with this

- How?
  - Add names and block periods on-chain into the portal registry

- When?
  - Pre-mainnet launch because it will be super hard to add post-mainnet

**Comment by corverroos** [comment]
Also `AttestInterval` see [issue](https://github.com/omni-network/omni/issues/1323)
