### ISSUE TITLE
Investigate possible goroutine leak

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1464]
Omega validators (1/3/4) are showing a steady increase in goroutines.

<img width="759" alt="image" src="https://github.com/user-attachments/assets/d4288233-33ec-4a0a-abe2-a6b87fc3cd66">

Note that validator02 doesn't.

**Comment by arajasek** [comment]
Okay, I've investigated this, and the cause is #1602. We can close this as completed and fix that issue.
