### ISSUE TITLE
OmniZero: Long tail rollups

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1475]
in order for a rollup to be integrated into Omni mainnet (let’s call it OmniZero for the sake of this discussion), it must pass some objective criteria: has some amount of TVL, is a stage X rollup (e.g.  has fraud proofs). Basically, they idea behind OmniZero is to create a highly secure (cryptoeconomically) platform for smart contract developers looking to deploy to the top N rollup platforms that offer general compute. We integrate new rollups as they hit the objective criteria.

However, this model doesn’t support permissionless rollup deployment. That’s okay, OmniZero solves the biggest smart contract developer friction point today

But there will be some devs looking for longer tail rollup support. Obviously, we don’t want to integrate the 120th rollup because 1) our validators will need to be running a node for it 
2) if it’s compromised many developers on our platform will have apps that are compromised (even if Omni itself isn’t compromised)

Our next big product launch could be OmniInfinity (names WIP) - which supports permissionless rollup deployment. You don’t get the heavily staked security of OmniZero, but that’s because you’re deploying / integrating a new/potentially experimental rollup

Protocol designs for this could vary, but basically could be an opt in “if you want this rollup to be supported you have to run a node/relayer (loosely defined) for it”

The two products could complement each other very nicely and cover the 2 developer segments I see growing over the next 5+ years: smart contract developers & rollup developers

**Comment by ttarsi** [comment]
closing as this is more of a long term product research exploration, not a specific problem to solve
