### ISSUE TITLE
Stop building binaries for Mac on Linux unless it is an official release

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1476]
We should stop building binaries for halo/relayer/monitor/cli etc for Mac arm on Linux VMs. Currently we do that on every single PR and also on merge to Master. In order to have faster CI pipelines (i.e. GH workflows), we might potentially:

* only build binaries for linux because this is what we use for our staging and test networks (release snapshots)
* we can still check if the code builds on other archs after we push our docker images to docker hub (similar to the way we run e2e tests now)
* build all binaries for official releases

**Comment by corverroos** [comment]
Done in https://github.com/omni-network/omni/pull/1927
