### ISSUE TITLE
Add governance support

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1487]
From [slack](https://omni-chain.slack.com/archives/C02HCJN6KNE/p1713870572736079?thread_ts=1713797193.796199&cid=C02HCJN6KNE)

So changing it requires “Governance” vote in traditional cosmosSDK. We don’t support governance yet, nor do we support changing genesis parameters in any other way. We would need to add support via:
- governance module and evmgovernance contract
- paramadmin evm contract and evmparam module in halo that reads log events and converts them into MsgParamUpdate.

**Comment by ttarsi** [comment]
Moving this to roadmap
