### ISSUE TITLE
Support eip1271 for operators

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1488]
From [slack](https://omni-chain.slack.com/archives/C05L7NJHSTH/p1714149406365869)

"The Eigen team is working on redoing their contracts to support eip1271. They're going into audits now, so supporting this will require some changes to our AVS contracts. Ultimately, the flow will be:
register with operator address, but in that registration, indicate your validator ecdsa key
use the validator ecdsa key for running the node software"

**Comment by corverroos** [comment]
Closing as this will be part of the "add support for eigen"
