### ISSUE TITLE
valsync db refactor

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1540]
Problem to solve:
 - [cosmos-orm](https://docs.cosmos.network/main/build/packages/orm) states that keeper DBs should use normalized design (1NF)
 - The valsync module currently follows partial 1NF?; Validators are duplicated per valset.
 - Pure 1NF would be: valset --many--> inclusion_with_power --> one validator
 
Proposed solutions:
 - Pick either proper 1NF 
 - or full denormalized (single valset table with `repeated Validator` field). <-- I'd suggest this even though cosmos says this is anti-pattern, since we already lookup the whole set. It therefore simplifies things.
 - or do nothing and stick to current solution

**Comment by arajasek** [comment]
I don't have a good sense of tradeoffs here, unfortunately, which makes me want to default to "do nothing".

**Comment by corverroos** [comment]
We decided to go with "do nothing" as there is no super strong reason to do either. We also know an DB upgrade will be required once we do "restaking" so we'll include any refactors then once we know more
