### ISSUE TITLE
Replay Protection: include consensus chain ID in siggys

### ISSUE THREAD

**Issue by arajasek** [omni-network/omni#1543]
We should consider including the consensus chain ID in signatures. This would serve as replay protection between our different networks, though that would only matter if we had the same validator address on 2 different networks.

**Comment by kirk-baird** [comment]
# The issue 

This is a good point. There should be some sort of domain separation that prevents signature replays on different networks. To do this we need to sign over something that is unique to the entire network. Then we need to validate the unique tag is correct during signature validation.

If there is a fork or some reason we have multiple `OmniPortal` contracts operating on a single chain they will both produce `XBlocks`. Any validator that is using the same key for both instances of `OmniPortal` can have their signature replayed on the other network. 

# My proposed solution is:

a) Include `omniChainId` in each `XBlockHeader`. Then add validation in the smart contracts in `xsubmit()` and consensus code for each signature verification step. Reject signatures with a different `omniChainId`. 

This should work as `omniChainId` would be unique per network fork including testnets and mainnets.

c) Discourage the use of validator keys on multiple networks wherever possible.
