### ISSUE TITLE
Use valsync in evidence module

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1578]
*Problem to Solve*
The binarybuilders report on `valsync` module highlighted an increased equivocation window (from the default 1 to arbitrary N) when validators are removed from the set. This is caused by the `valsync` module delaying `validator updates` for an arbitrary amount of time while it waits for valupdate xmsg to be approved.

*Proposed Solution*
Replace the evidence module `types.StakingKeeper` dependency (which is implemented by the cosmos staking module) with a custom adaptor that queries the `valsynckeeper.ActiveSetByHeight` instead of the staking keeper since it will have the actual active validator set. The other interface methods can be routed to staking keeper like normal.

Note this would require some depinject footwork to override the default cosmosSDK dependencies.

**Comment by corverroos** [comment]
ok, after digging some more into this, it seems like this isn’t going to work

The evidence keeper `handleEquivocationEvidence` does query the validator using `stakingKeeper.ValidatorByConsAddr`, and we could adapt that query our valsync module instead which will return the actual validator (that has been removed from staking module).

But the problem is that the slashing module is then subsequently both read from and written to to perform the slashing. But it will also not know about the validator. The slashing keeper hooks remove the pubkey as soon as the validator is removed from the staking module.

Also, the rewards/withdrawals/distribution module will probably not be able to include this “post-removal” slashing in its logic when calculating withdrawals.

My current conclusion: the only way to address the equivocation window issue (assuming we still want to wait arbitrary time for approved attestation) is to do the delay before the staking messages are processed by the staking keeper (not after). So something like:
- buffer the messages in valsync
- calculate the resulting valset they will produce (simulate staking keeper).
- wait for that valset to be attested
- then let the messages through to the staking keeper.

**Comment by arajasek** [comment]
Discussed this in team sync, some notes:
- as written above, fixing is complicated, and therefore risky
- the actual issue is relatively benign (we can't punish some bad behaviour from exiting validators)
- Mainnet V1 will have a small set of validators anyway
- attempting to fix this is probably riskier than just allowing status quo

Maybe fixed in the future.

**Comment by corverroos** [comment]
Closing as the proper solution is refactoring valsync to buffer and attest BEFORE staking module instead of AFTER.
