### ISSUE TITLE
Submodule hello-world-template lib dirs when running `omni developer new`

### ISSUE THREAD

**Issue by ttarsi** [omni-network/omni#1593]
*Problem to Solve*

When you run `omni developer new` it scaffolds a XDapp repo. This includes a `lib` dir, which references `forge-std` and `omni`, but unfortunately instead of submoduling them (which is standard in forge repos), it copies the whole repo.

*Proposed Solution*

Not sure

**Comment by kevinhalliday** [comment]
@ttarsi closing this. I tried `omni developer new`. It does use submodules, so it seems we are good.
