### ISSUE TITLE
Deploy portal sporadically fails with INITIALIZATION_FAILED

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1598]
*Problem to Solve*
Deploying public portals sporadically fails with INITIALIZATION_FAILED. The work around is to retry which usually succeeds.

See example staging [deploy](https://github.com/omni-network/ops/actions/runs/10142861428/job/28043067849) and arb_sepolia [tx](https://sepolia.arbiscan.io/tx/0x89b78b85e6f0fa983af127e6354fd9a5ad61794c1e6ec0229e46debd0bdd1507).
<img width="1131" alt="image" src="https://github.com/user-attachments/assets/ca12dab9-21c8-4e02-a862-c20d282ed082">

*Proposed Solution*
Unknown

**Comment by arajasek** [comment]
I think this is just an out of gas. Looking at the trace (attached) it fails with just about 14k gas left on a 4M gas transaction.

[arb_failure.md](https://github.com/user-attachments/files/16418696/arb_failure.md)

**Comment by corverroos** [comment]
Closing as this is a known limitation with very little effect as the workaround is to simply retry which solves it.
