### ISSUE TITLE
Voter to use consensus registry instead of evm registry

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1631]
*Problem to Solve*
The voter (and other processes) uses `netconf.AwaitOnChain` that queries the evm portal registry for supported chains. While cosmos onchain verification uses the consensus chain registry module supported chains. They are not identical, with consensus chain registry lagging by 1 block. This causes voter to submit votes too early, resulting in "check supported chain: missing conf levels" failures.

*Proposed Solution*
Refactor `netconf.AwaitOnChain` to use the consensus chain registry instead.
Instead of `*bindings.PortalRegistry` use the cprovider that queries `registry` module state.

**Comment by arajasek** [comment]
This requires adding some missing fields to the registry module, and is therefore now consensus critical.
