### ISSUE TITLE
Add ready healthcheck endpoint

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1682]
*Problem to Solve*
Omni node operators don't have a easy way to monitor the "readiness" of a halo node.

The best option at this point is the `halo_comet_synced` prometheus metric or the cometBFT `SyncInfo. catching_up` field. SyncInfo requires a special grpc clients and both require parsing of response.

A simple `curl halo:25560/ready` endpoint would provide great value if it includes a few simple "health checks":
 - CometBFT is synced 
 - CometBFT has peers
 - Geth connected
 - Geth is syned
 - Geth has peers

A prometheus metric that tracks this would also be great.

*Proposed Solution*
- Run `halo/app/monitor.go` loops every 10s. 
- Store results in a shared `ready` struct
- Query shared `ready` struct on `/ready` endpoint.
- Note that we should disable the default cometBFT prometheus server and serve our own on that port including above `/ready` and default prometheus `/metrics` endpoints.

**Comment by chmllr** [comment]
@corverroos two questions:

1. How about serving a simple json response like
```json
{
"CometBFT": "synced",
"CometBFT": "peers",
"Geth": {
     "connected": true,
     "synced": true,
     "peers": 10,
   }
}
```
so that it's both human-readable and parsable if needed later at some point?



2. Wdyt about calling the endpoint and the struct `/health` and `health` instead?

**Comment by corverroos** [comment]
`ready` follows the [k8s](https://kubernetes.io/docs/reference/using-api/health-checks/) style
![image](https://github.com/user-attachments/assets/cccefd21-46ee-4dfe-a2d5-363bbb2fdc6c)

**Comment by corverroos** [comment]
wrt returned struct, sure, we can do that in addition to status codes. I'd suggest to keep it simple and avoid nesting and to stick to general consensus/execution rather than implementations which may change (especially geth):
```
type ReadyResponse struct {
 ConsensusSynced bool `json:"comet_bft_synced"` // Return 503 is false
 ConsensusP2PPeers int  `json...` // Returns 503 if 0
 ExecutionConnected bool `json:..` // Returns 503 if false 
 ExecutionSynced bool `json...` // Returns 503 if false 
ExecutionP2PPeers int `json...` // Returns 503 if 0 
}
```

**Comment by chmllr** [comment]
Closed with https://github.com/omni-network/omni/pull/2035
