### ISSUE TITLE
fix account monitor frequent alerts

### ISSUE THREAD

**Issue by ttarsi** [omni-network/omni#1701]
#### Problem to Solve

Account monitor is frequently firing. This means that one or more of our accounts are frequently running out of funds. This means that either 1) that account's funding level is set too low, resulting in frequent alerts or 2) that account's funding level is fine, and something is wrong with how much it's spending.

#### Proposed Solution

Collect more data:
- which accounts are running out of funds
- on which chains?
- is it consistently the same chain/account?

**Comment by corverroos** [comment]
Staging chain stalled due to `old val set` issue since we didn’t fund it. I’m going to reduce self-delegation to allow more “relayer downtime”. Also going to increase relayer funding from 20 to 50.
