### ISSUE TITLE
Cache historical height when streaming attestations

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#1860]
#### Problem to Solve
When using cprovider to stream attestations, we do a full historical search when fetching each subsequent batch of attestations. 

But subsequent attestations will never be at an earlier height, so if the previous fetched height is known, the `lookback` step can be skipped.

This should decrease the `historical baseline` metric.

#### Proposed Solution
Cache the height used to fetch the next back of attestations when streaming.
Use this as lookback result when fetching the next batch

**Comment by sideninja** [comment]
Related thread https://omni-chain.slack.com/archives/C02HCJN6KNE/p1729174654091949
