### ISSUE TITLE
feat(docs): Cookbook Onboard (AI Assistant & Playground) Integration

### ISSUE THREAD

**Issue by ClockRide** [omni-network/omni#1867]
#### Problem to Solve

Developers using the Omni platform may experience difficulty in quickly finding specific information within the documentation or getting immediate assistance with Solidity coding tailored to Omni. This can slow down the development process and hinder productivity. Additionally, there's a need for an integrated environment where developers can experiment with and deploy smart contracts directly from the documentation.

#### Proposed Solution

Integrate the following tools into the Omni documentation website:

1. **Ask Cookbook AI Assistant**: Trained on all existing Omni resources—including source code and documentation—it provides quick, accurate answers to developer questions about building on Omni. It acts as both an enhanced documentation search tool and a Solidity coding co-pilot.

2. **Cookbook Onboard Playground**: Embed a Solidity IDE with smart contract templates alongside the AI assistant. This allows developers to search for and deploy Cookbook’s entire smart contract library without leaving the docs (including all popular OpenZeppelin contracts). Features include:
   - Deploying smart contracts or entire protocols to Omni directly from the documentation.
   - Serving as a free, no-code or low-code token and NFT launchpad.
   - Saving source code as Foundry, Hardhat, or Scaffold projects, or exporting to Remix or Chain IDE with one click.

**Preview Link:** [https://omni-docs-cookbook.vercel.app/](https://omni-docs-cookbook.vercel.app/)

![image](https://github.com/user-attachments/assets/14f91096-67d3-4f9f-a96b-2a877d778b28)
![image](https://github.com/user-attachments/assets/533f8deb-ce5b-4637-a2ee-4b0cb50da71b)

**Comment by corverroos** [comment]
Thanks for the contribution, but we are not considering any AI related tools at this stage.
