### ISSUE TITLE
Implement remaining contract admin actions

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#1920]
Prioritize and make sub task for the following

Needs Implementing

- [x] pause/unpause-xcall [HIGH]
- [x] pause/unpause-xcall to chain [HIGH]
- [x] pause/unpause-xsubmit  [HIGH]
- [x] pause/unpause-xsubmit from chain [HIGH]
- [x] pause / unpause bridge [HIGH]
- [ ] set XBlock / XMsg offset on a portal [MED]
- [ ] collect-fees from portal [MED]
- [ ] configure portals (all config xreceiptMaxErrorSize , xsubValsetCutoff , etc) [MED]
- [ ] configure fee oracle (protocolFee, baseGasLimit ) [LOW]
- [ ] enable/disable staking allow list [LOW]
- [x]  remaining upgrade actions (FeeOracleV1, Staking, Slashing, Upgrades , OmniGasPump , OmniGasStation , PortalRegistry …) [MED/HIGH - contract dependent]

**Comment by kc1116** [comment]
All admin commands that we need are implemented , closing.
