### ISSUE TITLE
typos in Build docs. 

### ISSUE THREAD

**Issue by pokhrelanmol** [omni-network/omni#2016]
#### Problem to Solve
In docs/build/Getting Started there is a small typo in two places. 

1. `env.` is mentioned instead of `.env` which can create confusion. 
2. In `Calculate xcall fee` section the command have a typo instead of `OP_RPC`, it is `OP_RCP`

#### Proposed Solution
Fix the typos.

**Comment by ttarsi** [comment]
Thanks! Addressing in #2048
