### ISSUE TITLE
Deploy gas pump contracts on mainnet

### ISSUE THREAD

**Issue by fabtreb** [omni-network/omni#2206]
- Deploy [GasPump](https://github.com/omni-network/omni/blob/main/contracts/core/src/interfaces/IOmniGasPump.sol) contract on mainnet
- Document usage of the gas pumps in smart contracts
- Configure the [gas pump ui](https://bridge.omni.network/refuel) to work with the deployed contracts

**Comment by Zodomo** [comment]
All contracts deployed and verified!

Gas Station [Implementation](https://omniscan.network/address/0xE49661b0a55542E20a39b2205a9883462A1725a4/contract/166/code) and [Proxy](https://omniscan.network/address/0x5A19272100949f9e8A4aD9D98f8C1070232de626/contract/166/code)

Gas Pumps

- Ethereum
    - Implementation [[ES]](https://etherscan.io/address/0xa2F831b93d1bA5eBf17803EF827189ed44efE51e#code) [[BS]](https://eth.blockscout.com/address/0xa2F831b93d1bA5eBf17803EF827189ed44efE51e?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/1/0xa2F831b93d1bA5eBf17803EF827189ed44efE51e/)
    - Proxy [[ES]](https://etherscan.io/address/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F#code) [[BS]](https://eth.blockscout.com/address/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/1/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F/)
- Arbitrum
    - Implementation [[ES]](https://arbiscan.io/address/0xa8faf21f43ee3ec1a3f98e8ccb595e32acf8d260#code) [[BS]](https://arbitrum.blockscout.com/address/0xa8faF21F43ee3Ec1a3f98E8cCB595E32Acf8d260?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/42161/0xa8faF21F43ee3Ec1a3f98E8cCB595E32Acf8d260/)
    - Proxy [[ES]](https://arbiscan.io/address/0x3cdf44dc0548fdd9304a4020624a5e216d8a861f#code) [[BS]](https://arbitrum.blockscout.com/address/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/42161/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F/)
- Optimism
    - Implementation [[ES]](https://optimistic.etherscan.io/address/0x9932b02f9a07aa1458c7790078c8ca586f196a6b#code) [[BS]](https://optimism.blockscout.com/address/0x9932b02f9A07Aa1458c7790078c8cA586F196A6B?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/10/0x9932b02f9A07Aa1458c7790078c8cA586F196A6B/)
    - Proxy [[ES]](https://optimistic.etherscan.io/address/0x3cdf44dc0548fdd9304a4020624a5e216d8a861f#code) [[BS]](https://optimism.blockscout.com/address/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/10/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F/)
- Base
    - Implementation [[ES]](https://basescan.org/address/0x53d95442e47049523a024b39895e1651b38001ec#code) [[BS]](https://base.blockscout.com/address/0x53D95442e47049523A024b39895e1651b38001eC?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/8453/0x53D95442e47049523A024b39895e1651b38001eC/)
    - Proxy [[ES]](https://basescan.org/address/0x3cdf44dc0548fdd9304a4020624a5e216d8a861f#code) [[BS]](https://base.blockscout.com/address/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F?tab=contract) [[Sourcify]](https://repo.sourcify.dev/contracts/full_match/8453/0x3cdF44dC0548fDD9304A4020624A5e216D8A861F/)
