### ISSUE TITLE
Support forked anvils in manifest

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#2210]
#### Problem to Solve
We want to deploy mainnet, but we want to first dry run the deploy process. This will harden the mainnet deploy and safe money and time.

#### Proposed Solution
Add a overrides to manifest such that anvil chains get started with --fork commands.

**Comment by kevinhalliday** [comment]
Closing this for now - we are not going to use it as a mainnet manifest smoke test.
Though it could be a nice feature for devnet.
