### ISSUE TITLE
Investigate sporadic not ready spikes 

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#2315]
#### Problem to Solve
The archive01 node in omega (and possibly others) show sporadic not ready spikes. We need to investigate this and identify the root cause and possibly fix the issue

#### Proposed Solution
TBD

**Comment by chmllr** [comment]
The conclusion was that on all cases we observed so far, nodes experienced either a restart or the consensus height didn't increase for many seconds. So there is nothing to do so far.
