### ISSUE TITLE
Dedup relayer streams

### ISSUE THREAD

**Issue by corverroos** [omni-network/omni#2321]
#### Problem to Solve
See [ADR](https://www.notion.so/omni-network/Dedup-relayer-streams-12769a99643a80c7b78cea02dbea35ba)

**Comment by kc1116** [comment]
Slack [thread](https://omni-chain.slack.com/archives/C02HCJN6KNE/p1730368439553649?thread_ts=1730356199.896509&cid=C02HCJN6KNE) related to original implementation

**Comment by corverroos** [comment]
Closing this as "not done" as we did two implementations that didn't solve the problem. This feels quite complex (caching often is). Hopefully #1860 solves the problem in the short to medium term.
